# Generated by Django 4.1.7 on 2023-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0005_alter_brand_image_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/uploads/categories'),
        ),
    ]
