# Generated by Django 4.1.7 on 2023-03-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
