# Generated by Django 4.1.7 on 2023-03-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0009_tryon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArjunVaas.product'),
        ),
    ]
