# Generated by Django 4.1.7 on 2023-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0011_banner_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
