# Generated by Django 4.1.7 on 2023-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0014_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='try_on_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
