# Generated by Django 4.1.7 on 2023-05-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0015_product_price_product_try_on_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='try_on_enabled',
            new_name='try_on_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='try_on_image2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='try_on_image3',
            field=models.BooleanField(default=False),
        ),
    ]
