# Generated by Django 4.1.7 on 2023-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0017_remove_product_try_on_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='try_on_image1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='try_on_image2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='try_on_main_image',
            field=models.BooleanField(default=True),
        ),
    ]
