# Generated by Django 4.1.7 on 2023-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArjunVaas', '0020_product_try_on_image1_product_try_on_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_try_on_image1_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_try_on_image2_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_try_on_main_image_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='try_on_image1',
            field=models.ImageField(blank=True, default='', upload_to='static/uploads/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='try_on_image2',
            field=models.ImageField(blank=True, default='', upload_to='static/uploads/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='try_on_main_image',
            field=models.ImageField(blank=True, default='', upload_to='static/uploads/products'),
        ),
    ]
