# Generated by Django 4.1.7 on 2023-03-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_profile_gender_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='uploads/profiles'),
        ),
    ]
